//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDApaint.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CART
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CART()
        {
            this.CART_ITEM = new HashSet<CART_ITEM>();
        }
    
        public int CART_ID { get; set; }
        public Nullable<int> USER_ID { get; set; }
        public Nullable<System.DateTime> DATE_ORDER { get; set; }
        public string SHIP_NAME { get; set; }
        public string SHIP_MOBILE { get; set; }
        public string SHIP_ADDRESS { get; set; }
        public string SHIP_EMAIL { get; set; }
        public string SHIP_MESSAGES { get; set; }
        public Nullable<int> TOTAL_MONEY { get; set; }
        public Nullable<int> STATUS { get; set; }
        public Nullable<int> SALE_ID { get; set; }
        public string REASON_CANCEL { get; set; }
        public Nullable<int> DELIVERY_ITEM_ID { get; set; }
        public Nullable<int> DELIVERY_COST { get; set; }
        public Nullable<System.DateTime> ESTIMATED_DATE_DELIVERY { get; set; }
        public Nullable<int> DISCOUNT_VALUE { get; set; }
    
        public virtual DELIVERY_ITEM DELIVERY_ITEM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CART_ITEM> CART_ITEM { get; set; }
        public virtual USER USER { get; set; }
    }
}
