//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDApaint.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class COLOR_GROUP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public COLOR_GROUP()
        {
            this.COLOR_GROUP_NEWS = new HashSet<COLOR_GROUP_NEWS>();
            this.SUB_COLOR_GROUP = new HashSet<SUB_COLOR_GROUP>();
        }
    
        public int COLOR_GROUP_ID { get; set; }
        public string COLOR_GROUP_NAME { get; set; }
        public string COLOR_GROUP_CODE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COLOR_GROUP_NEWS> COLOR_GROUP_NEWS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SUB_COLOR_GROUP> SUB_COLOR_GROUP { get; set; }
    }
}
