//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDApaint.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class COLOR_GROUP_NEWS
    {
        public int COLOR_GROUP_NEWS_ID { get; set; }
        public Nullable<int> COLOR_GROUP_ID { get; set; }
        public Nullable<int> NEWS_ID { get; set; }
    
        public virtual COLOR_GROUP COLOR_GROUP { get; set; }
        public virtual NEWS NEWS { get; set; }
    }
}
