//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDApaint.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class COLOR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public COLOR()
        {
            this.PRODUCT_COLOR = new HashSet<PRODUCT_COLOR>();
        }
    
        public int COLOR_ID { get; set; }

        [Required(ErrorMessage ="Vui lòng nhập mã màu sơn")]
        public string COLOR_CODE { get; set; }

        [Required(ErrorMessage ="Vui lòng nhập tên màu sơn")]
        public string COLOR_NAME { get; set; }

        [Required(ErrorMessage ="Vui lòng nhập mã RGB của màu sơn")]
        public string COLOR_RGB_NAME { get; set; }
        public Nullable<int> SUB_COLOR_GROUP_ID { get; set; }
    
        public virtual SUB_COLOR_GROUP SUB_COLOR_GROUP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUCT_COLOR> PRODUCT_COLOR { get; set; }
    }
}
