//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDApaint.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;


    public partial class DELIVERY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DELIVERY()
        {
            this.DELIVERY_ITEM = new HashSet<DELIVERY_ITEM>();
        }
    
        public int DELIVERY_ID { get; set; }
        [Required(ErrorMessage ="Vui lòng nhập tên công ty")]
        public string DELIVERY_COMPANY_NAME { get; set; }

        [Required(ErrorMessage ="Vui lòng nhập số điện thoại")]
        [DataType(DataType.PhoneNumber,ErrorMessage ="Đinh dạng số điện thoại không đúng")]
        [RegularExpression(@"^([0-9]{10})$", ErrorMessage = "Số điện thoại không đúng định dạng.")]
        public string DELIVERY_PHONE { get; set; }

        [Required(ErrorMessage ="Vui lòng nhập địa chỉ")]
        public string DELIVERY_ADDRESS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DELIVERY_ITEM> DELIVERY_ITEM { get; set; }
    }
}
