//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDApaint.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMPORT_ORDER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IMPORT_ORDER()
        {
            this.IMPORT_ORDER_DETAIL = new HashSet<IMPORT_ORDER_DETAIL>();
        }
    
        public int ID { get; set; }
        public Nullable<System.DateTime> DATE_IMPORT { get; set; }
        public Nullable<int> TOTAL { get; set; }
        public Nullable<int> PERSON_IMPORT_ID { get; set; }
        public Nullable<int> SUPPLIER_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IMPORT_ORDER_DETAIL> IMPORT_ORDER_DETAIL { get; set; }
        public virtual PERSON_IMPORT PERSON_IMPORT { get; set; }
        public virtual SUPPLIER SUPPLIER { get; set; }
    }
}
