//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDApaint.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class IMPORT_ORDER_DETAIL
    {
        public int ID { get; set; }
        public Nullable<int> IMPORT_ID { get; set; }

        public Nullable<int> PRODUCT_ID { get; set; }
        
        public Nullable<int> IMPORT_AMOUNT { get; set; }

        [Required(ErrorMessage = "Vui lòng nhập số lượng")]
        [Range(10, 999, ErrorMessage = "Số lượng ít nhất là 10 và nhiều nhất là 999")]
        public Nullable<int> IMPORT_AMOUNT_REAL { get; set; }

        [Required(ErrorMessage ="Vui lòng nhập giá ")]
        public Nullable<int> IMPORT_PRICE { get; set; }
        public Nullable<int> IMPORT_INTO_MONEY { get; set; }
        public Nullable<int> IMPORT_UNIT_ID { get; set; }
    
        public virtual IMPORT_ORDER IMPORT_ORDER { get; set; }
        public virtual UNIT_PRODUCT UNIT_PRODUCT { get; set; }
        public virtual PRODUCT PRODUCT { get; set; }
    }
}
