//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDApaint.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class MEMBERSHIP_TYPE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MEMBERSHIP_TYPE()
        {
            this.USERs = new HashSet<USER>();
        }
    
        public int ID { get; set; }
        
        [Required(ErrorMessage ="Vui lòng nhập tên loại thành viên")]
        public string MEMBERSHIP_TYPE1 { get; set; }
        [Required(ErrorMessage ="Vui lòng nhập giá trị giảm giá")]
        public Nullable<int> DISCOUNT_VALUE { get; set; }
        public Nullable<int> DISCOUNT_UNIT_ID { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }

        [Required(ErrorMessage ="Vui lòng nhập ngày hết hạn")]    
        public Nullable<System.DateTime> VALID_UNTIL { get; set; }

        [Required(ErrorMessage ="Vui lòng chọn")]
        public Nullable<bool> FREE_SHIPPING_ACTIVE { get; set; }

        [Required(ErrorMessage ="Vui lòng nhập điểm tối thiểu cho loại thành viên")]
        public Nullable<int> MIN_POINT { get; set; }

        [Required(ErrorMessage = "Vui lòng nhập điểm tối đa cho loại thành viên")]
        public Nullable<int> MAX_POINT { get; set; }
    
        public virtual DISCOUNT_UNIT DISCOUNT_UNIT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USER> USERs { get; set; }
    }
}
