//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDApaint.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DATABASELVTN1Entities : DbContext
    {
        public DATABASELVTN1Entities()
            : base("name=DATABASELVTN1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ADMIN> ADMINs { get; set; }
        public virtual DbSet<CART> CARTs { get; set; }
        public virtual DbSet<CART_ITEM> CART_ITEM { get; set; }
        public virtual DbSet<COLOR> COLORs { get; set; }
        public virtual DbSet<COLOR_GROUP> COLOR_GROUP { get; set; }
        public virtual DbSet<COLOR_GROUP_NEWS> COLOR_GROUP_NEWS { get; set; }
        public virtual DbSet<COMMENT> COMMENTs { get; set; }
        public virtual DbSet<COMMENT_NEWS> COMMENT_NEWS { get; set; }
        public virtual DbSet<DELIVERY> DELIVERies { get; set; }
        public virtual DbSet<DELIVERY_ITEM> DELIVERY_ITEM { get; set; }
        public virtual DbSet<DELIVERY_TYPE> DELIVERY_TYPE { get; set; }
        public virtual DbSet<DISCOUNT_UNIT> DISCOUNT_UNIT { get; set; }
        public virtual DbSet<FEEDBACK> FEEDBACKs { get; set; }
        public virtual DbSet<IMPORT_ORDER> IMPORT_ORDER { get; set; }
        public virtual DbSet<IMPORT_ORDER_DETAIL> IMPORT_ORDER_DETAIL { get; set; }
        public virtual DbSet<MEMBERSHIP_TYPE> MEMBERSHIP_TYPE { get; set; }
        public virtual DbSet<NEWS> NEWS { get; set; }
        public virtual DbSet<NEWS_TYPE> NEWS_TYPE { get; set; }
        public virtual DbSet<PERSON_IMPORT> PERSON_IMPORT { get; set; }
        public virtual DbSet<PRODUCER> PRODUCERs { get; set; }
        public virtual DbSet<PRODUCT> PRODUCTs { get; set; }
        public virtual DbSet<PRODUCT_COLOR> PRODUCT_COLOR { get; set; }
        public virtual DbSet<PRODUCT_DISCOUNT> PRODUCT_DISCOUNT { get; set; }
        public virtual DbSet<PRODUCT_TYPE> PRODUCT_TYPE { get; set; }
        public virtual DbSet<SUB_COLOR_GROUP> SUB_COLOR_GROUP { get; set; }
        public virtual DbSet<SUPPLIER> SUPPLIERs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<UNIT_PRODUCT> UNIT_PRODUCT { get; set; }
        public virtual DbSet<USER> USERs { get; set; }
    }
}
