//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDApaint.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class NEWS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NEWS()
        {
            this.COLOR_GROUP_NEWS = new HashSet<COLOR_GROUP_NEWS>();
        }
    
        public int NEWS_ID { get; set; }

       
        public Nullable<System.DateTime> NEWS_DATE { get; set; }

        [Required(ErrorMessage ="Vui lòng nhập tiêu đề")]
        public string NEWS_TITLE { get; set; }

        [Required(ErrorMessage="Vui lòng nhập nội dung tóm tắt")]
        public string NEWS_SUMMARY { get; set; }

        [Required(ErrorMessage ="Vui lòng nhập nội dung bài viết")]
        public string NEWS_CONTENT { get; set; }

        [Required(ErrorMessage ="Vui lòng chọn ảnh cho bài viết")]
        public string NEWS_IMG { get; set; }
        public Nullable<int> ADMIN_ID { get; set; }
        public Nullable<int> NEWS_TYPE_ID { get; set; }

        [Required(ErrorMessage ="Vui lòng chọn trạng thái")]
        public Nullable<bool> STATUS { get; set; }
    
        public virtual ADMIN ADMIN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COLOR_GROUP_NEWS> COLOR_GROUP_NEWS { get; set; }
        public virtual NEWS_TYPE NEWS_TYPE { get; set; }
    }
}
