//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDApaint.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class PRODUCT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRODUCT()
        {
            this.CART_ITEM = new HashSet<CART_ITEM>();
            this.COMMENTs = new HashSet<COMMENT>();
            this.IMPORT_ORDER_DETAIL = new HashSet<IMPORT_ORDER_DETAIL>();
            this.PRODUCT_COLOR = new HashSet<PRODUCT_COLOR>();
        }
    
        public int PRODUCT_ID { get; set; }

        [StringLength(100, MinimumLength = 6, ErrorMessage = "Tên tài ít nhất 6 kí tự và nhiều nhất là 100 kí tự")]
        [Required(ErrorMessage = "Vui lòng nhập tên sản phẩm")]
        public string PRODUCT_NAME { get; set; }


        [Range(1,99999999,ErrorMessage ="Giá sản phẩm phải lớn hơn 1 và nhỏ hơn 99999999")]
        [Required(ErrorMessage = "Vui lòng nhập giá bán sản phẩm")]
        public Nullable<int> PRICE { get; set; }
        
        public Nullable<int> AMOUNT { get; set; }

        [Required(ErrorMessage ="Vui lòng chọn ngày sản xuất")]
        public Nullable<System.DateTime> DATE_OF_MANUFACTURE { get; set; }

        [Range(1,60,ErrorMessage ="Hạn sử dụng không dưới 1 tháng và trên 60 tháng")]
        [Required(ErrorMessage = "Vui lòng chọn hạn sử dụng")]
        public Nullable<int> LIMITED_USE { get; set; }

        [Required(ErrorMessage ="Vui lòng nhập mô tả cho sản phẩm")]
        public string DESCRIPTION { get; set; }

        [Required(ErrorMessage ="Vui lòng chọn hình")]
        public string IMAGE { get; set; }

        [Required(ErrorMessage ="Vui lòng nhập thể tích")]
        [Range(1,999,ErrorMessage ="Thể tích phải lớn hơn 1 và nhỏ hơn 999")]
        public Nullable<int> NET { get; set; }

        [Required(ErrorMessage ="Vui lòng nhập code chống hàng giả")]
        public string CODE_AUTH { get; set; }

        public Nullable<int> STATUS { get; set; }

        public string SPECIFICATION { get; set; }
        public Nullable<int> PRODUCT_TYPE_ID { get; set; }
        public Nullable<int> PRODUCER_ID { get; set; }
        public Nullable<int> DISCOUNT { get; set; }
        public Nullable<int> BUYING { get; set; }
        public Nullable<int> SELL { get; set; }
        public Nullable<int> DISCOUNT_VALUE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CART_ITEM> CART_ITEM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMMENT> COMMENTs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IMPORT_ORDER_DETAIL> IMPORT_ORDER_DETAIL { get; set; }
        public virtual PRODUCER PRODUCER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUCT_COLOR> PRODUCT_COLOR { get; set; }
        public virtual PRODUCT_DISCOUNT PRODUCT_DISCOUNT { get; set; }
        public virtual PRODUCT_TYPE PRODUCT_TYPE { get; set; }
    }
}
