//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDApaint.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCT_COLOR
    {
        public int PRODUCT_COLOR_ID { get; set; }
        public Nullable<int> PRODUCT_ID { get; set; }
        public Nullable<int> COLOR_ID { get; set; }
    
        public virtual COLOR COLOR { get; set; }
        public virtual PRODUCT PRODUCT { get; set; }
    }
}
