//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDApaint.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class PRODUCT_DISCOUNT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRODUCT_DISCOUNT()
        {
            this.PRODUCTs = new HashSet<PRODUCT>();
        }
    
        public int ID { get; set; }

        [Required(ErrorMessage ="Vui lòng nhập giá trị giảm giá")]
        public Nullable<int> DISCOUNT_VALUE { get; set; }
        public Nullable<int> DISCOUNT_UNIT_ID { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }

        [Required(ErrorMessage ="Vui lòng chọn ngày hết hạn")]
        public Nullable<System.DateTime> UNTIL_VALID { get; set; }

        public Nullable<int> MAXIMUM_DISCOUNT_VALUE { get; set; }
        public Nullable<int> MINIMUM_ORDER_VALUE { get; set; }

        [Required(ErrorMessage ="Vui lòng nhập mô tả cho khuyến mãi này")]
        public string DESCRIPTION { get; set; }

        [Required(ErrorMessage ="Vui lòng chọn trạng thái")]
        public Nullable<bool> STATUS { get; set; }

        [Required(ErrorMessage ="Vui lòng nhập tên COUPON CODE")]
        public string COUPON_CODE { get; set; }
    
        public virtual DISCOUNT_UNIT DISCOUNT_UNIT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUCT> PRODUCTs { get; set; }
    }
}
