//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDApaint.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUB_COLOR_GROUP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SUB_COLOR_GROUP()
        {
            this.COLORs = new HashSet<COLOR>();
        }
    
        public int SUB_COLOR_GROUP_ID { get; set; }
        public string SUB_COLOR_GROUP_CODE { get; set; }
        public string SUB_COLOR_GROUP_NAME { get; set; }
        public Nullable<int> COLOR_GROUP_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COLOR> COLORs { get; set; }
        public virtual COLOR_GROUP COLOR_GROUP { get; set; }
    }
}
