//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDApaint.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class USER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USER()
        {
            this.CARTs = new HashSet<CART>();
            this.COMMENTs = new HashSet<COMMENT>();
            this.FEEDBACKs = new HashSet<FEEDBACK>();
        }
    
        public int ID { get; set; }

        [Required(ErrorMessage ="Không để trống tên tài khoản")]
        [Remote("IsAlreadyUsername","User",HttpMethod ="POST",ErrorMessage ="Tên tài khoản đã tồn tại !!!")]
        public string USERNAME { get; set; }

        [Required(ErrorMessage ="Không được để trống Password")]
        [DataType(DataType.Password)]
        [StringLength(100,MinimumLength =6,ErrorMessage ="Password không được ít hơn 6 ký tự")]
        public string PASSWORD { get; set; }

        [Required(ErrorMessage ="Vui lòng nhập số điện thoại")]
        [DataType(DataType.PhoneNumber,ErrorMessage = "Số điện thoại không đúng định dạng")]
        [RegularExpression(@"^([0-9]{10})$", ErrorMessage = "Số điện thoại không đúng định dạng.")]
        public string PHONE { get; set; }

        [Required(ErrorMessage ="Vui lòng nhập địa chỉ")]
        public string ADDRESS { get; set; }

        [Required(ErrorMessage = "Không được để trống email")]
        [DataType(DataType.EmailAddress)]
        [EmailAddress(ErrorMessage = "Định dạng email không đúng")]
        [Remote("IsAlreadyEmail", "User", HttpMethod = "POST", ErrorMessage = "Email đã tồn tại !!!")]
        public string EMAIL { get; set; }

        [Required(ErrorMessage = "Vui lòng nhập hộ tên đầy đủ")]
        public string FULLNAME { get; set; }

        [Required(ErrorMessage ="Vui lòng chọn giới tính")]
        public Nullable<byte> GENDER { get; set; }
        
        public Nullable<System.DateTime> DATE_REGISTER { get; set; }
        public string RESET_PASSWORD_CODE { get; set; }
        public Nullable<int> MEMBERSHIP_TYPE_ID { get; set; }
        public Nullable<int> TOTAL_TRANSACTION { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CART> CARTs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMMENT> COMMENTs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FEEDBACK> FEEDBACKs { get; set; }
        public virtual MEMBERSHIP_TYPE MEMBERSHIP_TYPE { get; set; }
    }
}
